// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package index

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "strings"

//  /*background: radial-gradient( #222148 20%, transparent 21% ,transparent 79%, #222148 80%);*/

func Body() templ.CSSClass {
	var templ_7745c5c3_CSSBuilder strings.Builder
	templ_7745c5c3_CSSBuilder.WriteString(`font-family:'Lexend Variable', sans-serif;`)
	templ_7745c5c3_CSSBuilder.WriteString(`background-image:url('data:image/svg+xml,<svg width="247.89212mm" height="248.8756mm" viewBox="0 0 247.89212 248.8756" opacity="0.05" version="1.1" id="svg5" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg"><defs id="defs2" /><g id="layer1" transform="translate(-27.361241,-29.403773)"><rect style="fill:%23083a42;fill-opacity:1;stroke:%2327c700;stroke-width:0.426;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:56;stroke-dasharray:none;stroke-opacity:1;paint-order:normal" id="rect31" width="52.678379" height="52.678379" x="84.668121" y="-72.016068" ry="3.9963174" rx="3.9963174" transform="rotate(55)" /><rect style="fill:%230c5460;fill-opacity:1;stroke:%2327c700;stroke-width:0.426456;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:56;stroke-dasharray:none;stroke-opacity:1;paint-order:normal" id="rect31-3" width="52.678379" height="52.678379" x="138.97997" y="-81.3974" ry="3.9963174" rx="3.9963174" transform="rotate(55)" /><rect style="fill:%2313889b;fill-opacity:1;stroke:%2327c700;stroke-width:0.426456;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:56;stroke-dasharray:none;stroke-opacity:1;paint-order:normal" id="rect31-6" width="52.678379" height="52.678379" x="94.680458" y="-18.131142" ry="3.9963174" rx="3.9963174" transform="rotate(55)" /><rect style="fill:%23106e7d;fill-opacity:1;stroke:%2327c700;stroke-width:0.426456;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:56;stroke-dasharray:none;stroke-opacity:1;paint-order:normal" id="rect31-3-7" width="52.678379" height="52.678379" x="149.12616" y="-27.254137" ry="3.9963174" rx="3.9963174" transform="rotate(55)" /></g><g id="layer2" /></svg>');`)
	templ_7745c5c3_CSSBuilder.WriteString(`background-size:2em 2em;`)
	templ_7745c5c3_CSSBuilder.WriteString(`height:100svh;`)
	templ_7745c5c3_CSSBuilder.WriteString(`display:flex;`)
	templ_7745c5c3_CSSBuilder.WriteString(`flex-direction:column;`)
	templ_7745c5c3_CSSBuilder.WriteString(`justify-content:space-between;`)
	templ_7745c5c3_CSSID := templ.CSSID(`Body`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}
